### ISSUE TITLE
Add support for whosonfirst/go-reader-findingaid

### ISSUE THREAD

**Issue by thisisaaronland** [whosonfirst/go-whosonfirst-browser#30]
* https://github.com/whosonfirst/go-reader-findingaid

There are three parts to this: 

* Decide whether to build finding aid database at start up or just assume it is present
* Update all the code to use new reader
* Decide how to manage / schedule updates to finding aid database

TBD:

* Does this necessitate a "v4" bump
* How does this work when run as a Lambda function

For bonus points:

* Query the finding aid database over the wire using https://github.com/aaronland/go-sqlite-vfs/blob/main/vfs.go

**Comment by straup** [comment]
Ongoing in: https://github.com/whosonfirst/go-whosonfirst-browser/tree/findingaid-v2
